version: '3.5'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
      - ./logs:/var/log/nginx
    working_dir: /var/www/html
    ports:
      - 80:80
    links:
      - php
  php:
    image: php:fpm
    volumes:
      - ./web:/var/www/html
    working_dir: /var/www/html
    links:
      - mysql
  mysql:
    image: mysql:latest
      #container_name: telnet_mysql_3306
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./.my.cnf:/root/.my.cnf
    environment:
      #PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_ROOT_HOST: "%"

