version: '3.5'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
        #- ./logs:/var/log/nginx
    working_dir: /var/www/html
    ports:
      - 80:80
  php:
    image: psydiamond/php:7.4-upd-fpm
    volumes:
      - ./web:/var/www/html
    working_dir: /var/www/html
  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./.my.cnf:/root/.my.cnf
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_ROOT_HOST: "%"

