version: '3.5'
services:
  docker-compouse_nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/:/var/www/html
    ports:
      - '80:80'
